language: go
sudo: false
go_import_path: github.com/techknowlogick/go-oauth2-xorm
go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
